In [152]:
import numpy as np

In [153]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?

In [154]:
number_of_negs = a < 0
count = np.count_nonzero(number_of_negs)
count

4

2. How many positive numbers are there?

In [155]:
number_of_pos = a > 0
count = np.count_nonzero(number_of_pos)
count

5

3. How many even positive numbers are there?

In [157]:
even_and_pos_numbers = a > 0 & a % 2 == 0
count = np.count_nonzero(even_and_pos_numbers)
count

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [54]:
number_of_pos = a > 0
count_pos = np.count_nonzero(number_of_pos)
print(f"Amount of positive numbers: ",count_pos)
number_of_even = a % 2 == 0
count_even = np.count_nonzero(number_of_even)
print(f"Amount of even numbers: ", count_even)

Amount of positive numbers:  5
Amount of even numbers:  8


4. If you were to add 3 to each data point, how many positive numbers would there be?

In [160]:
add_three = a + 3
new_positive_numbers = add_three > 0

count = np.count_nonzero(new_positive_numbers)
count

10

5. If you squared each number, what would the new mean and standard deviation be?

In [56]:
sqred_numbers = a ** 2
print(np.mean(sqred_numbers))
print(np.std(sqred_numbers))

74.0
144.0243035046516


6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [57]:
data_centering = a - a.mean()
data_centering

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [162]:
data_centering.mean()

0.0

7. Calculate the z-score for each data point. Recall that the z-score is given by: Z = (x − μ) / σ

In [58]:
mean = np.mean(a)
std = np.std(a)
zscore = (a-mean)/std
zscore

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [163]:
z = (a - a.mean()) / a.std()
z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [165]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

- Use python's built in functionality/operators to determine the following:

- Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [166]:
sum_of_a = sum(a)
sum_of_a

55

- Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [167]:
min_of_a = min(a)
min_of_a

1

- Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [168]:
max_of_a = max(a)
max_of_a

10

- Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [169]:
mean_of_a = sum(a) / len(a)
mean_of_a

5.5

- Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [170]:
def product_of_a(a):
          total =1
          for i in a:
             total=total*i
          return total
print(product_of_a(a))

3628800


In [171]:
total = 1
for n in a:
    total *= n
total

3628800

- Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [92]:
def squares_of_a(a):
    return [i ** 2 for i in a]
print(squares_of_a(a))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [172]:
[n ** 2 for n in a]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

- Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [173]:
[n for n in a if n % 2 != 0]

[1, 3, 5, 7, 9]

In [96]:
def odds_in_a(a) :
    new_a = []
    for i in a :
        if i % 2 != 0 :
            new_a.append(i)
    return new_a
print(odds_in_a(a))

[1, 3, 5, 7, 9]


- Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [97]:
def evens_in_a(a) :
    new_a = []
    for i in a :
        if i % 2 == 0 :
            new_a.append(i)
    return new_a
print(evens_in_a(a))

[2, 4, 6, 8, 10]


In [175]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

- Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

sum_of_b = 0

for row in b:

    sum_of_b += sum(row)


In [99]:
b = np.array(b)
b.sum()

33

- Exercise 2 - refactor the following to use numpy. 

min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  



In [101]:
b.min()

3

- Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])




In [102]:
b.max()

8

- Exercise 4 - refactor the following using numpy to find the mean of b

mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))



In [103]:
b.mean()

5.5

- Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

product_of_b = 1

for row in b:

    for number in row:
    
        product_of_b *= number

In [104]:
np.prod(b)
#np.prod multiplies everything in the array (put this in notes)

20160

- Exercise 6 - refactor the following to use numpy to find the list of squares 

squares_of_b = []

for row in b:

    for number in row:
    
        squares_of_b.append(number**2)

In [110]:
squares_of_b = [x**2 for x in b]
squares_of_b

[array([ 9, 16, 25]), array([36, 49, 64])]

- Exercise 7 - refactor using numpy to determine the odds_in_b

odds_in_b = []

for row in b:

    for number in row:
    
        if(number % 2 != 0):
        
            odds_in_b.append(number)

In [114]:
odds_in_b = (b[b%2!=0])
odds_in_b

array([3, 5, 7])

- Exercise 8 - refactor the following to use numpy to filter only the even numbers

evens_in_b = []

for row in b:

    for number in row:
    
        if(number % 2 == 0):
        
            evens_in_b.append(number)

In [115]:
evens_in_b = (b[b%2==0])
evens_in_b

array([4, 6, 8])

- Exercise 9 - print out the shape of the array b.

In [116]:
b.shape

(2, 3)

- Exercise 10 - transpose the array b.

In [117]:
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

- Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [118]:
np.reshape(b, (1, 6))

array([[3, 4, 5, 6, 7, 8]])

- Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [119]:
np.reshape(b, (6, 1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [176]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

- HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

In [126]:
c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- Exercise 1 - Find the min, max, sum, and product of c.

In [135]:
min_of_c = c.min()
max_of_c = c.max()
sum_of_c = c.sum()
product_of_c = np.prod(c)

print(f"Minimum of c is ", min_of_c)
print(f"Maximum of c is ", max_of_c)
print(f"The sum of c is ", sum_of_c)
print(f"The product of c is ", product_of_c)

Minimum of c is  1
Maximum of c is  9
The sum of c is  45
The product of c is  362880


- Exercise 2 - Determine the standard deviation of c.

In [136]:
stdev_of_c = c.std()
print(f"Standard deviation of c is ", stdev_of_c)

Standard deviation of c is  2.581988897471611


- Exercise 3 - Determine the variance of c.

In [138]:
variance_of_c = np.var(c)
variance_of_c

6.666666666666667

- Exercise 4 - Print out the shape of the array c

In [139]:
c.shape

(3, 3)

- Exercise 5 - Transpose c and print out transposed result.

In [143]:
transposed_c = np.transpose(c)
print(transposed_c)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


- Exercise 6 - Get the dot product of the array c with c. 

In [144]:
dot_product_of_c = np.dot(c, c)
dot_product_of_c

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [177]:
np.dot(c, c).sum()

729

- Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [149]:
product_of_sum = np.prod(c)
transposed_product = np.transpose(product_of_sum)
sum_of_product = product_of_sum + transposed_product
sum_of_product

725760

- Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [178]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

- Exercise 1 - Find the sine of all the numbers in d


In [179]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

- Exercise 2 - Find the cosine of all the numbers in d


In [180]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

- Exercise 3 - Find the tangent of all the numbers in d


In [185]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

- Exercise 4 - Find all the negative numbers in d


In [183]:
d = np.array(d)
d[d < 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

- Exercise 5 - Find all the positive numbers in d


In [184]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

- Exercise 6 - Return an array of only the unique numbers in d.


In [186]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

- Exercise 7 - Determine how many unique numbers there are in d.


In [187]:
d.shape

(3, 6)

- Exercise 8 - Print out the shape of d.


In [189]:
d.T.shape

(6, 3)

- Exercise 9 - Transpose and then print out the shape of d.


In [190]:
np.transpose(d)


array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

- Exercise 10 - Reshape d into an array of 9 x 2