# -----------------------------Numpy-----------------------------------

Numpy is a library for representing and working with large and multi-dimensional arrays. Most other libraries in the data-science ecosystem depend on numpy, making it one of the fundamental data science libraries.

Numpy provides a number of useful tools for scientific programming, and in this lesson, we'll take a look at some of the most common.

Convention is to import the numpy module as np.

## So What?
- Numpy is oneof the main reasons why Python so powerful and popular for scientific computing and analysis.
- It is super fast.
    - numpy arrays are implments in the c programming language
        - you dont need to lear c programming language
            - but because it is not always talking through python it makes is super fast.
                - c is "closer to the metal" than python
                - assemby is "closer to the metal" than c
                - and processor instruction sets == are the metal!
- Most popular linear algebra library in Python
    - read the math and do your work in numpy
- Provide loop-like behaviour w/o the overhead loops or lists comprehensions(vectorized operations)
    - Super helpful right off the bat
- Provides the same type of work as working off a list + loop + conditional behavior for filering arrays
    - Super helpful right off the bat
- Great skill to put on a resume

In [2]:
import numpy as np
    #Customary across all is to alias inumpy as np

In [3]:
%%timeit
[x ** 2 for x in range(1, 1_000_000)]
    #tis runs a few times and gives us back the average time it takes to run the cell

243 ms ± 2.92 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%%timeit
np.arange(1, 1_000_000) ** 2
    #tis runs a few times and gives us back the average time it takes to run the cell

598 µs ± 12.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
370 / 3.04

121.71052631578947

In [6]:
#Make our first numpy array
x = [1, 2, 3, 4, 5]
type(x)

list

In [7]:
x = [1, 2, 3, 4, 5]
x= np.array(x)
x, type(x)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

nd = n-dimensional array

In [8]:
#example of dimensions
x.shape
#shape is a property not a function
#shape tells us the shape of our n-dimensitonal array

(5,)

In [9]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
matrix * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [11]:
type(matrix)

numpy.ndarray

In [12]:
matrix.shape

(3, 3)

In [13]:
#List index syntax works on numpy arrays!
matrix[0]
#1-dimension

array([1, 2, 3])

In [14]:
matrix[0][0]
#2-dimension
# matrix[1st row][1st number in 1st row]

1

In [15]:
#the above can also be written as
matrix[0, 0]

1

In [16]:
first_row = matrix[0]
first_row

array([1, 2, 3])

In [17]:
first_element = first_row[0]
first_element

1

In [18]:
#can also use splicing syntax
x, x[1:3]

(array([1, 2, 3, 4, 5]), array([2, 3]))

In [19]:
a = np.array(range(1, 100))
a
#will not hit 100

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

- one set of [ ] means it is one dimensional if it has 2 it is 2 dimensions and so on and so forth

In [20]:
x.sum(), x.mean(), x.min(), x.max(), x.std()

(15, 3.0, 1, 5, 1.4142135623730951)

In [21]:
a.sum(), a.mean(), a.min(), a.max(), a.std()

(4950, 50.0, 1, 99, 28.577380332470412)

In [22]:
#median is differenc (and there are some other functions that work similarly)
np.median(x)

3.0

In [23]:
np.median(a)

50.0

- a whole bunch of these notations will work with the array.( ) but some things like median you have to call off the numpy library itself

In [24]:
b = np.array([2, 3, 4, 5])
should_include_elements = np.array([False, True, False, True])
b[should_include_elements]

array([3, 5])

        - this can be used to filter your results so at each corresponding indexes in b to should inlude elements turn on or off the element.
            - False = off
            - True = on

In [25]:
should_include_elements = np.array([False, True, True])
matrix[should_include_elements]
#first element off seecond element on third element on

array([[4, 5, 6],
       [7, 8, 9]])

### Arrays of Booleans == the beating heart of filter/transforming arrays
    - this is how we can do loop like stuff w/o loops
    - This spell is called "boolean Masking" and folks may "array filtering" or "indexing"

In [26]:
x = np.array([1, 2, 3, 4, 5])

In [27]:
x == 3
#does your array contain the number three?
#shows false for the numbers that are not 3 and True for the pone that is

array([False, False,  True, False, False])

In [28]:
x < -9
# All false cause none of the numbers are less than -9

array([False, False, False, False, False])

In [29]:
x > 3
# all over 3 are true rest are false

array([False, False, False,  True,  True])

In [30]:
x % 2 == 0
# even numbers are true odds are false

array([False,  True, False,  True, False])

- creating an array of booleans and using iit to filter our resuls is called Boolean Masking

In [31]:
only_threes = x == 3
x[only_threes]

array([3])

In [32]:
# we dones need the extra variable, hower, we can do the folloing:
# I read this code almost like SQL in my head:
# select x where x is less than ero
x[x == 3]

array([3])

In [33]:
# Select x where x is less than zero
x[x <0]

array([], dtype=int64)

In [34]:
#select x where x is greater than 3
x[x > 3]

array([4, 5])

In [35]:
# select x where x divided by 2 leaves no remainder
evens_from_x = x[x % 2 == 0]
evens_from_x

array([2, 4])

In [36]:
# in python admissions test, there was a quesion called 'remove_evens' where you write a function that remvoe evens
# in base python this is a loop with conditional and another operation to append to a list comprehenstions

def remove_evens(x):
    x = np.array(x)
    return x[x % 2 == 0]

remove_evens([2, 3, 34, 5, 6, 24, 442, 24, 12, 3, 24, 3, 3, 23, 23, 23, 10])

array([  2,  34,   6,  24, 442,  24,  12,  24,  10])

In [37]:
remove_evens(a)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [38]:
remove_evens(b)

array([2, 4])

### Intro to Vectorization

- similar in the fact it is doing loop like behavior on an array without the loop


In [39]:
x = np.zeros(10)
x
#np.zeros is helpful as a linear algebra zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
x + 1
#introducting to life post loops

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
# lets make a random array of numbers (integers)
# stat is inclusinve, end is exclusie
# so the following line is like rolling a 20 sided die
x = np.random.randint(1, 21)
x

19

In [42]:
#3rd argument is the size or number of random numbers
x = np.random.randint(1, 21, 10)
x
# (starting number, ending number, number of times rolled)

array([19, 15,  4,  9,  7,  6,  3, 19, 16, 12])

In [43]:
# lets make python fall on its falce
a = [ 1, 2, 3]

# in python, how would we add one to eveyry item on htis list?
[n + 1 for n in a]

[2, 3, 4]

In [44]:
x + 1

array([20, 16,  5, 10,  8,  7,  4, 20, 17, 13])

In [45]:
x / 10

array([1.9, 1.5, 0.4, 0.9, 0.7, 0.6, 0.3, 1.9, 1.6, 1.2])

In [46]:
x * x

array([361, 225,  16,  81,  49,  36,   9, 361, 256, 144])

In [47]:
x * x - 2 + 3 * x

array([416, 268,  26, 106,  68,  52,  16, 416, 302, 178])

In [48]:
x

array([19, 15,  4,  9,  7,  6,  3, 19, 16, 12])

- it is intuative to take and array of numbers and add, subtract, multiple, etc.
- this is like a spreadsheet
- If you look at what we are doing this kind of notation is like what you would see in linear algebra

In [49]:
# Theres way more linear algebra features
np.dot(x,x)

1538

In [50]:
np.linalg.norm(x)

39.21734310225516

In [51]:
np.array(original_array) + 1

NameError: name 'original_array' is not defined

In [52]:
beatles = np.array(["Ringo", "George", "Pual", "John"])
beatles

array(['Ringo', 'George', 'Pual', 'John'], dtype='<U6')

In [53]:
beatles == "Ringo"

array([ True, False, False, False])

In [54]:
beatles[beatles != "Ringo"]

array(['George', 'Pual', 'John'], dtype='<U6')

# ---------------------------Indexing-----------------------------------

Numpy provides an array type that goes above and beyond what Python's built-in lists can do.

We can create a numpy array by passing a list to the np.array function:

In [55]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

We can create a multi-dimensional array by passing a list of lists to the array function

In [56]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Referencing elements in numpy arrays at it's most basic is the same as referencing elements in Python lists.

In [57]:
a[0]

1

In [58]:
print('a    == {}'.format(a))
print('a[0] == {}'.format(a[0]))
print('a[1] == {}'.format(a[1]))
print('a[2] == {}'.format(a[2]))

a    == [1 2 3]
a[0] == 1
a[1] == 2
a[2] == 3


However, multidimensional numpy arrays are easier to index into. To obtain the element at the second column in the second row, we would write:

In [59]:
matrix[1, 1]

5

To get the first 2 elements of the last 2 rows:

In [60]:
matrix[1:, :2]

array([[4, 5],
       [7, 8]])

Arrays can also be indexed with a boolean sequence used to indicate which values should be included in the resulting array.

In [61]:
should_include_elements = [True, False, True]
a[should_include_elements]

array([1, 3])

Note that the boolean sequence must the the same length as the array being indexed

# ---------------------Vectorized Operations-------------------------

Another useful feature of numpy arrays is vectorized operations.

If we wanted to add 1 to every element in a list, without numpy, we can't simply add 1 to the list, as that will result in a TypeError.

In [62]:
original_array = [1, 2, 3, 4, 5]
try:
    original_array + 1
except TypeError as e:
    print('An Error Occured!')
    print(f'TypeError: {e}')

An Error Occured!
TypeError: can only concatenate list (not "int") to list


Instead, we might write a for loop or a list comprehension:

In [63]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = []
for n in original_array:
    array_with_one_added.append(n + 1)
print(array_with_one_added)

[2, 3, 4, 5, 6]


In [64]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = [n + 1 for n in original_array]
print(array_with_one_added)

[2, 3, 4, 5, 6]


Vectorizing operations means that operations are automatically applied to every element in a vector, which in our case will be a numpy array. So if we are working with a numpy array, we can simply add 1:

In [65]:
original_array = np.array([1, 2, 3, 4, 5])
original_array + 1

array([2, 3, 4, 5, 6])

This works the same way for the other basic arithmatic operators as well.

In [66]:
my_array = np.array([-3, 0, 3, 16])

print('my_array      == {}'.format(my_array))
print('my_array - 5  == {}'.format(my_array - 5))
print('my_array * 4  == {}'.format(my_array * 4))
print('my_array / 2  == {}'.format(my_array / 2))
print('my_array ** 2 == {}'.format(my_array ** 2))
print('my_array % 2  == {}'.format(my_array % 2))

my_array      == [-3  0  3 16]
my_array - 5  == [-8 -5 -2 11]
my_array * 4  == [-12   0  12  64]
my_array / 2  == [-1.5  0.   1.5  8. ]
my_array ** 2 == [  9   0   9 256]
my_array % 2  == [1 0 1 0]


Not only are the arithmatic operators vectorized, but the same applies to the comparison operators.

In [67]:
my_array = np.array([-3, 0, 3, 16])

print('my_array       == {}'.format(my_array))
print('my_array == -3 == {}'.format(my_array == -3))
print('my_array >= 0  == {}'.format(my_array >= 0))
print('my_array < 10  == {}'.format(my_array < 10))

my_array       == [-3  0  3 16]
my_array == -3 == [ True False False False]
my_array >= 0  == [False  True  True  True]
my_array < 10  == [ True  True  True False]


Knowing what we know about indexing numpy arrays, we can use the comparison operators to select a certain subset of an array.

For example, we can get all the positive numbers in my_array like so:

In [68]:
my_array[my_array > 0]

array([ 3, 16])

# ----------------------In-Depth Example-----------------------------

As another example, we could obtain all the even numbers like this:

In [69]:
my_array[my_array % 2 == 0]

array([ 0, 16])

To better understand how this is all working let's go through the above example in a little more detail.


The first expression that gets evaluated is this:

In [70]:
my_array % 2

array([1, 0, 1, 0])

Which results in an array of 1s and 0s. Then the array of 1s and 0s is compared to 0 with the == operator, producing an array of True or False values.

In [71]:
result = my_array % 2
result == 0

array([False,  True, False,  True])

Lastly, we use this array of boolean values to index into the original array, giving us only the values that are evenly divisible by 2.

In [72]:
step_1 = my_array % 2
step_2 = step_1 == 0
step_3 = my_array[step_2]

step_3

array([ 0, 16])

Put another way, here is how the expression is evaluated:

In [73]:
print('1. my_array[my_array % 2 == 0]')
print('    - the original expression')
print('2. my_array[{} % 2 == 0]'.format(my_array))
print('    - variable substitution')
print('3. my_array[{} == 0]'.format(my_array % 2))
print('    - result of performing the vectorized modulus 2')
print('4. my_array[{}]'.format(my_array % 2 == 0))
print('    - result of comparing to 0')
print('5. {}[{}]'.format(my_array, my_array % 2 == 0))
print('    - variable substitution')
print('6. {}'.format(my_array[my_array % 2 == 0]))
print('    - our final result')

1. my_array[my_array % 2 == 0]
    - the original expression
2. my_array[[-3  0  3 16] % 2 == 0]
    - variable substitution
3. my_array[[1 0 1 0] == 0]
    - result of performing the vectorized modulus 2
4. my_array[[False  True False  True]]
    - result of comparing to 0
5. [-3  0  3 16][[False  True False  True]]
    - variable substitution
6. [ 0 16]
    - our final result


# -------------------------Array Creation------------------------------

Numpy provides several methods for creating arrays, we'll take a look at several of them.

np.random.randn can be used to create an array of specified length of random numbers drawn from the standard normal distribution.

In [74]:
np.random.randn(10)

array([-0.30950264, -0.28869139,  0.44899556,  0.27474374, -0.52853664,
       -0.03604363,  0.14506149, -3.18356541, -0.15572588,  0.70222344])

We can also pass a second argument to this function to define the shape of a two dimensional array.

In [75]:
np.random.randn(3, 4)

array([[ 0.4734689 ,  0.09555128,  1.25879997,  1.75760056],
       [-1.17698214,  0.29792019,  0.27488502, -1.334657  ],
       [-1.46961625,  0.66663147, -0.44720077,  0.09959918]])

If we wish to draw from a normal distribution with mean μ and standard deviation σ, we'll need to apply some arithmetic. Recall that to convert from the standard normal distribution, we'll need to multiply by the standard deviation, and add the mean.

In [76]:
mu = 100
sigma = 30

sigma * np.random.randn(20) + mu

array([157.49329109, 152.47871635,  67.38193579,  79.15615763,
        78.00652741,  53.26402204, 121.30666879, 128.83938985,
       160.31701883, 102.56370397, 143.79800419,  88.11039864,
       106.29562943, 143.02819294, 111.07098485,  86.56223486,
        81.40403136,  98.27817435, 115.18553131,  78.52832336])

The zeros and ones functions provide the ability to create arrays of a specified size full or either 0s or 1s, and the full function allows us to create an array of the specified size with a default value.

In [77]:
print('np.zeros(3)    == {}'.format(np.zeros(3)))
print('np.ones(3)     == {}'.format(np.ones(3)))
print('np.full(3, 17) == {}'.format(np.full(3, 17)))

np.zeros(3)    == [0. 0. 0.]
np.ones(3)     == [1. 1. 1.]
np.full(3, 17) == [17 17 17]


We can also use these methods to create multi-dimensional arrays by passing a tuple of the dimensions of the desired array, instead of a single integer value.

In [78]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Numpy's arange function is very similar to python's builtin range function. It can take a single argument and generate a range from zero up to, but not including, the passed number.

In [79]:
np.arange(4)

array([0, 1, 2, 3])

We can also specify a starting point for the range:

In [80]:
np.arange(1, 4)

array([1, 2, 3])

As well as a step:

In [81]:
np.arange(1, 4, 2)

array([1, 3])

Unlike python's builtin range, numpy's arange can handle decimal numbers

In [82]:
np.arange(3, 5, 0.5)

array([3. , 3.5, 4. , 4.5])

The linspace method creates a range of numbers between a minimum and a maximum, with a set number of elements.

In [83]:
print('min: 1, max: 4, length = 4 -- {}'.format(np.linspace(1, 4, 4)))
print('min: 1, max: 4, length = 7 -- {} '.format(np.linspace(1, 4, 7)))

min: 1, max: 4, length = 4 -- [1. 2. 3. 4.]
min: 1, max: 4, length = 7 -- [1.  1.5 2.  2.5 3.  3.5 4. ] 


Note that here the maximum is inclusive.

# -------------------------Array Methods------------------------------

Numpy arrays also come with built-in methods to make many mathematical operations easier.

In [84]:
a = np.array([1, 2, 3, 4, 5])

Some of the most common are:

    - .min

In [85]:
a.min()

1

    - .max

In [86]:
a.max()

5

.mean

In [87]:
a.mean()

3.0

.sum

In [88]:
a.sum()

15

In [89]:
a.std()

1.4142135623730951

-multiplies all in a array

In [92]:
np.prod(a)

120

-transposes the array

In [ ]:
np.transpose(a)

-reshapes an array (rows, columns)

In [95]:
np.reshape(a, (1, 5))

array([[1, 2, 3, 4, 5]])

In [96]:
np.reshape(a, (5, 1))

array([[1],
       [2],
       [3],
       [4],
       [5]])

- shows current shape

In [99]:
a.shape

(5,)

-finds variance of an array

In [100]:
np.var(a)

2.0

- finds dot product of array(s) --- np.dot(array 1, array 2) --- can be the same array too

In [102]:
np.dot(a, a)

55

In [104]:
np.unique(a)

array([1, 2, 3, 4, 5])

In [107]:
a.T.shape
#flips it on its side

(5,)