In [2]:
import numpy as np
import pandas as pd

# Simulations =Monte Caro Method

## How to run a simulatikon with python/numpy/pandas
1. Figure out a way to represent our data
2. crete a matrix of random data, rows = simulation, coulumns = trial
    - for example rolling 2 dice 10,000 times means rows = 10,000  and columns = 2 bc we roll 2 dice each time
3. apply an aggregates function, row-wise to get the results of the simulation
4. apply a final aggregate to get our probability

In [3]:
#lets answer questions experimentally rather than theoretically
#whats the probability of flipping heads on a coin

#lets find a coins 100,000 times and figure out the probability of lfipping heads

#lets find a way to represent our data
outcomes = ["Heads", "Tails"]
number_of_simulations = 100_000

flips = np.random.choice(outcomes, size = number_of_simulations)
flips

array(['Tails', 'Heads', 'Tails', ..., 'Tails', 'Heads', 'Heads'],
      dtype='<U5')

In [4]:
#sum up how many tmes heads is flipped

(flips == "Heads").sum()

49907

In [5]:
#mean of how many tmes heads is flipped

(flips == "Heads").mean()

0.49907

In [6]:
#Another examples:
#what is the probab9ility of rolling a 5 on a 6 sided die?

#Step 1, represent our datas outcomes:
outcomes = [1, 2, 3, 4, 5, 6]

#Step 3, create the data
n_simulations = 10_000

rolls = np.random.choice(outcomes, size = n_simulations)

#what are the chances we roll a 5
(rolls == 5).mean()

0.167

In [7]:
#what are the chances we roll a 5 or 6 on a 6 sided die?
(rolls >= 5).mean()

0.3347

In [8]:
#what are the chances we roll less than a 3
(rolls < 3).mean()

0.3359

In [9]:
#What are the chances we roll somehing other than 3
(rolls != 3).mean()

0.8337

## lets roll 2 dice at once
1. figure out a way to represent date
2. create matrix of random data, rows==simulations, columns==trials
3. applyb an aggregate row-wise to get the results of each simulation
4. apply a final aggregate (probably the .mean) to get our probability

In [10]:
# Simulations = the number of times we run an experiment
#trials = the number of things in each experiment

In [11]:
#What are the odds of rolling snake eyes on two dice?

#Step1: represent data
outcomes = [1, 2, 3, 4, 5, 6]

#step 2 create a matrix of random data where rows = simulations and columns = trials
n_simulations = 1_000_000
n_trials = 2 #b/c we are rolling 2 dice each time

#size arguemtn can set out simulation and trial size
rolls = np.random.choice(outcomes, size = (n_simulations, n_trials))
rolls

array([[5, 4],
       [6, 3],
       [2, 2],
       ...,
       [3, 3],
       [3, 2],
       [5, 4]])

In [12]:
#Step 3: apply an aggrgate row-wise
sum_of_rolls = rolls.sum(axis=1)
    #axis= 1 means sum across the rows
    #snake eyes will sum to 2
sum_of_rolls
    #axis=1 is rows axis=0 is columns (DEFAULTS TO 0)

array([9, 9, 4, ..., 6, 5, 9])

In [13]:
#step 4
#add up all the times that an experiment produces the sum of 2 (which is snake eyes cause 1 + 1 = 2)
(sum_of_rolls == 2).mean()

0.027747

In [14]:
theoretical = 1/6 * 1/6
print(f"Our theroetical probability of rolling snake eyes is 1/6 * 1/6, which is {theoretical}")

Our theroetical probability of rolling snake eyes is 1/6 * 1/6, which is 0.027777777777777776


In [15]:
#What is the probability of rolling a 7 on 2 dice
#can produce by 1+6, 2+5, 3+4, 4+3, 5+2, 6+1

#step 1L represent our outcomes
outcomes = [1, 2, 3, 4, 5, 6]

#step 2 create a matrix of random data where rows = simulations and columns = trials
#size = (simulations, trials)
# size =. (experiments, number of dice per experiment)
rolls = np.random.choice(outcomes, size = (10_000, 2))

#step 3: apply a row-wise aggregate
sume_of_rolls = rolls.sum(axis = 1)

(sum_of_rolls == 7).mean()

0.166344

In [16]:
#Possible sum outcomes from 2 dice
x = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

y = [(sum_of_rolls == n).mean() for n in sum_of_rolls]

In [17]:
sum_of_rolls[:10]

array([ 9,  9,  4,  4,  8,  8,  2, 10,  7,  9])

In [18]:
y[:10]

[0.111268,
 0.111268,
 0.082845,
 0.082845,
 0.13869,
 0.13869,
 0.027747,
 0.08336,
 0.166344,
 0.111268]

In this lesson, we will work through several examples of using random numbers to simulate real-world scenarios.

# setting out own probabitlity

In [11]:
#lets answer questions experimentally rather than theoretically
#whats the probability of flipping heads on a coin

#lets find a coins 100,000 times and figure out the probability of lfipping heads

#lets find a way to represent our data
outcomes = ["Heads", "Tails"]
flips = np.random.choice(outcomes, size = (10_000, 1), p=[0.55, 0.45]) # 55% chance heads 45% tails

(flips == "Heads").mean()

0.5473

In [12]:
# what are the chances of flipping 2 heads in a row?
flips = np.random.choice(outcomes, size = (10_000, 2), p = [0.55, 0.45])
flips

array([['Tails', 'Tails'],
       ['Heads', 'Tails'],
       ['Tails', 'Heads'],
       ...,
       ['Tails', 'Heads'],
       ['Tails', 'Heads'],
       ['Heads', 'Heads']], dtype='<U5')

In [14]:
#it'll be a bit easier to check for two hEADS IF THE HEAD = 1 AND TAIL = 0
# MIGHT AS WELL TURN A BINARY INTO A BINARY

# LETS say Heads is 1 and tails is 0

outcomes = [1, 0]
flips = np.random.choice(outcomes, size = (10_000, 2), p = [0.55, 0.45])
flips

array([[1, 1],
       [1, 0],
       [0, 1],
       ...,
       [1, 1],
       [0, 0],
       [1, 0]])

In [15]:
# axis = 1 to sum across the rows, so we have as many sums as we do coin flips
num_of_heads = flips.sum(axis = 1)
num_of_heads

array([2, 1, 1, ..., 2, 0, 1])

In [16]:
(num_of_heads == 2).mean()

0.3014

In [17]:
#What if it was a fair coin
outcomes = [1, 0]
flips = np.random.choice(outcomes, size = (10_000, 2))
num_of_heads = flips.sum(axis = 1)
(num_of_heads == 2).mean()

0.2531

In [18]:
# lets ad some boolean logic probabilties


In [20]:
#lets say we have an average of 0 and a stdev of 20

numbers = np.random.randint(-50, 100, 100_000)
numbers

array([-12,  29,  45, ..., -45,  94,  61])

In [22]:
# what is the probability that any number is negative
(numbers < 0).mean()

0.33435

In [24]:
# what is the prbability a number is odd
(numbers %2 != 0).mean()

0.49933

In [25]:
# what is the prbability a number is even
(numbers %2 == 0).mean()

0.50067

In [30]:
# what is the prbability a number is odd and negative
# is_negative
is_negative = (numbers < 0)
is_odd = (numbers %2 != 0)
(is_odd & is_negative).mean()

0.16571

In [35]:
((numbers < 0) & (numbers %2 != 0)).mean()

0.16571

In [ ]:
# what is the probability of having your number being even or positive

In [34]:
is_positive = (numbers > 0)
is_even = (numbers % 2 == 0)
(is_positive | is_even).mean()
# the | is the or cant spell it out here or you will get an error

0.83429

In [36]:
((numbers > 0) | (numbers % 2 == 0)).mean()

0.83429

In [37]:
# rolling 2 dice at a time, what is the probability of rolling an odd then an even?

#step 1 represent the world in Pandas/Numpy
first_die = np.random.choice ([1, 2, 3, 4, 5, 6], size =  100_000)
second_die = np.random.choice ([1, 2, 3, 4, 5, 6], size =  100_000)

first_die, second_die

(array([6, 1, 3, ..., 2, 2, 1]), array([6, 4, 1, ..., 1, 6, 3]))

In [49]:
# we need to represent the results of the first die as an array of bolleans
first_die_is_odd = (first_die % 2 != 0)
first_die_is_odd

array([False,  True,  True, ..., False, False,  True])

In [48]:
second_die_is_even = (second_die % 2 == 0)
second_die_is_even

array([ True,  True, False, ..., False,  True, False])

In [47]:
first_odd_second_even = (first_die_is_odd & second_die_is_even)
first_odd_second_even.mean()

0.25011

In [8]:
%matplotlib inline
import numpy as np
import pandas as pd

np.random.seed(29)

Generating Random Numbers with Numpy
The `numpy.random module provides a number of functions for generating random numbers.

- `np.random.choice`: selects random options from a list
- `np.random.uniform`: generates numbers between a given lower and upper bound
- `np.random.random`: generates numbers between 0 and 1
- `np.random.randn`: generates numbers from the standard normal distribution
- `np.random.normal`: generates numbers from a normal distribution with a specified mean and standard deviation

Example Problems

`Carnival Dice Rolls
You are at a carnival and come across a person in a booth offering you a game of "chance" (as people in booths at carnivals tend to do).`

`You pay 5 dollars and roll 3 dice. If the sum of the dice rolls is greater than 12, you get 15 dollars. If it's less than or equal to 12, you get nothing.`

`Assuming the dice are fair, should you play this game? How would this change if the winning condition was a sum greater than or equal to 12?`

To simulate this problem, we'll write the python code to simulate the scenario described above, then repeat it a large amount of times.

One way we can keep track of all the simulations is to use a 2-dimensional matrix. We can create a matrix where each row represents one "trial". Each row will have 3 columns, representing the 3 dice rolls.

In [ ]:
n_trials = nrows = 10_000
n_dice = ncols = 3

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

Here we used the `choice` function to randomly select an element out of the list of the number 1-6, effectively simulating a dice roll. The second argument supplied to `choice` is the total number of dice to roll. Once we have generated all the dice rolls, we use the `.reshape` method to create our matrix with 3 columns and 10,000 rows.

Now that we have all of the simulated dice rolls, we want to get the sum of the dice rolls for each trial. To do this, we can use the .sum function and specify that we want the sum of every row (as opposed to the sum of all the numbers, or the sum by column) with the `axis` key word argument.

In [ ]:
sums_by_trial = rolls.sum(axis=1)
sums_by_trial

Let's pause here for a minute and visualize the data we have:

In [3]:
simulation_example1(sums_by_trial)

NameError: name 'simulation_example1' is not defined

The area shaded in lightblue represents our chance of winning, that is, the number of times that the sum of 3 dice rolls is greater than 12.

We can now convert each value in our array to a boolean value indicating whether or not we won:

In [4]:
wins = sums_by_trial > 12
wins

NameError: name 'sums_by_trial' is not defined

To calculate an overall win rate, we can treat each win as a 1 and each loss as 0, then take the average of the array:

In [5]:
win_rate = wins.astype(int).mean()
win_rate

NameError: name 'wins' is not defined

Now that we know our win rate, we can calculate the expected profit:

In [ ]:
cost = 5
expected_profit = expected_winnings - cost
expected_profit

So we would expect, based on our simulations, on average, to lose a little over a dollar everytime we play this game.

To answer the last part of the question, we can recalculate our win rate based on the sums being greater than or equal to 12:

In [ ]:
wins = sums_by_trial >= 12
win_rate = wins.astype(int).mean()
expected_winnings = win_rate * 15
cost = 5
expected_profit = expected_winnings - cost
expected_profit



If our win condition changes to the sum being greater than or equal to 12, then, based on our simulations, on average, we expect to win about 58 cents.

### No Rest or Relaxation
`There's a 30% chance my son takes a nap on any given weekend day. What is the chance that he takes a nap at least one day this weekend? What is the probability that he doesn't nap at all?`

Let's first do a little bit of setup:

In [6]:
p_nap = .3
ndays = ncols = 2
n_simulated_weekends = nrows = 10**5

To simulate the results from many weekends, we'll create a 2 x 10,000 matrix, with 2 being the number of days in a weekend and 10,000 being the number of simulations we want to run.

To determine whether or not a nap is taken on a given day, we'll generate a random number between 0 and 1, and say that it is a nap if it is less than our probability of taking a nap.

In [7]:
data = np.random.random((nrows, ncols))
data

array([[0.55205244, 0.41682549],
       [0.2617375 , 0.29129195],
       [0.33374247, 0.46972586],
       ...,
       [0.34319534, 0.80917653],
       [0.26405481, 0.41164982],
       [0.56866057, 0.23839418]])

In [8]:
naps = data < p_nap
naps

array([[False, False],
       [ True,  True],
       [False, False],
       ...,
       [False, False],
       [ True, False],
       [False,  True]])

Now that we have each day as either true or false, we can take the sum of each row to find the total number of naps for the weekend. When we sum an array of boolean values, numpy will treat True as 1 and False as 0.

In [9]:
naps.sum(axis=1)

array([0, 2, 0, ..., 0, 1, 1])

Now we have the results of our simulation, an array where each number in the array represents how many naps were taken in a two day weekend.

In [10]:
viz.simulation_example2(naps)

NameError: name 'viz' is not defined

We can use this to answer our original questions, what is the probability that at least one nap is taken?

In [11]:
(naps.sum(axis=1) >= 1).mean()

0.51059

What is the probability no naps are taken?

In [13]:
(naps.sum(axis=1) == 0).mean()

0.48941

### One With Dataframes
Let's take a look at one more problem:

`What is the probability of getting at least one 3 in 3 dice rolls?`

To simulate this, we'll use a similar strategy to how we modeled the dice rolls in the previous example, but this time, we'll store the results in a pandas dataframe so that we can apply a lambda function that will check to see if one of the rolls was a 3.

In [14]:
n_simulations = nrows = 10**5
n_dice_rolled = ncols = 3

rolls = np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols)

(pd.DataFrame(rolls)
 .apply(lambda row: 3 in row.values, axis=1)
 .mean())

0.42188

Let's break down what's going on here:

1. First we assign values for the number of rows and columns we are going to use
2. Next we create the rolls variable that holds a 3 x 10,000 matrix where each element is a randomly chosen number from 1 to 6
3. Lastly we create a dataframe from the rolls

    a. `pd.DataFrame(rolls)` converts our 2d numpy matrix to a pandas DataFrame
    
    b. `.apply(...` applies a function to each row in our dataframe, because we specified axis=1, the function will be called with each row as it's argument. The body of the function checks to see if the value 3 is in the values of the row, and will return either True or False
    
    c. `.mean()` takes our resulting series of boolean values, and treats True as 1 and False as 0, to give us the average rate of Trues, in this case, the simulated probability of getting a 3 in 3 dice rolls.