1. Create a new file named model_evaluation.py or model_evaluation.ipynb for these exercises.

## ✓

2. Given the following confusion matrix, evaluate (by hand) the model's performance.

|               | pred dog   | pred cat   |
|:------------  |-----------:|-----------:|
| actual dog    |         46 |         7  |
| actual cat    |         13 |         34 |




- **Values**
    - TP = 46
    - FP = 13
    - TN = 34
    - FN = 7

- **Accuracy**
    - (TP + TN) / (TP + FP + TN + FN)
        - (46 + 34) / (46 + 13 + 34 + 7)
            - 80 / 100
                - .8
- **Precision**
    - (TP) / (TP + FP)
        - 46 / (46 + 13)
            - 46 / 59
                - .77966
- **Recall**
    - (TP) / (TP + FN)
        - 46 / (46 + 7)
            - 46 / 53
                - .8679
- **F1 Score**
    - (2 * Precision * Recall) / (Precision + Recall)
        - (2 * .77966 * .8679) / (.77966 + .8679)
            - 1.3533 / 1.6476
                - .8214

a. In the context of this problem, what is a false positive?


- FP = 13
    - predicted a dog 
    - actually a cat

b. In the context of this problem, what is a false negative?


- FN = 7
    - predicted cat
    - actually dog

c. How would you describe this model?
    


3. You are working as a datascientist working for Codeup Cody Creator (C3 for short), a rubber-duck manufacturing plant.



In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from pydataset import data

- Unfortunately, some of the rubber ducks that are produced will have defects. Your team has built several models that try to predict those defects, and the data from their predictions can be found here.



In [81]:
rubber_ducks = pd.read_csv('c3.csv')
rubber_ducks.head()

actual     model1  model2     model3
0  No Defect  No Defect  Defect  No Defect
1  No Defect  No Defect  Defect     Defect
2  No Defect  No Defect  Defect  No Defect
3  No Defect     Defect  Defect     Defect
4  No Defect  No Defect  Defect  No Defect

In [82]:
rubber_ducks.actual.value_counts()

No Defect    184
Defect        16
Name: actual, dtype: int64

- Use the predictions dataset and pandas to help answer the following questions:


In [83]:
from sklearn.metrics import confusion_matrix

In [84]:
confusion_matrix(rubber_ducks.actual, rubber_ducks.model1,
                 labels = ['No Defect', 'Defect'])

array([[182,   2],
       [  8,   8]])

In [85]:
confusion_matrix(rubber_ducks.actual, rubber_ducks.model2,
                 labels = ['No Defect', 'Defect'])

array([[103,  81],
       [  7,   9]])

In [86]:
confusion_matrix(rubber_ducks.actual, rubber_ducks.model3,
                 labels = ['No Defect', 'Defect'])

array([[98, 86],
       [ 3, 13]])

In [87]:
model_recall = (subset.actual == subset.model1).mean()
print(f"Model 1's recall is {model_recall:.2%}")

Model 1's recall is 80.00%


In [90]:
model_recall = (subset.actual == subset.model2).mean()
print(f"Model 2's recall is {model_recall:.2%}")

Model 2's recall is 40.00%


In [91]:
model_recall = (subset.actual == subset.model3).mean()
print(f"Model 3's recall is {model_recall:.2%}")

Model 3's recall is 80.00%


- An internal team wants to investigate the cause of the manufacturing defects. They tell you that **they want to identify as many of the ducks that have a defect as possible**. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?
- Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, and portraying C3 in a bad light. The PR team has decided to launch a program that gives customers with a defective duck a vacation to Hawaii. **They need you to predict which ducks will have defects, but tell you they really don't want to accidentally give out a vacation package when the duck really doesn't have a defect.** Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

In [92]:
subset = rubber_ducks[rubber_ducks.model1 == 'Defect']

model_precision = (subset.actual == subset.model1).mean()

print(f"Model 1's precision is {model_precision:.2%}")

Model 1's precision is 80.00%


In [95]:
subset = rubber_ducks[rubber_ducks.model2 == 'Defect']

model_precision = (subset.actual == subset.model2).mean()

print(f"Model 2's precision is {model_precision:.2%}")

Model 2's precision is 10.00%


In [96]:
subset = rubber_ducks[rubber_ducks.model3 == 'Defect']

model_precision = (subset.actual == subset.model3).mean()

print(f"Model 3's precision is {model_precision:.2%}")

Model 3's precision is 13.13%


4. You are working as a data scientist for Gives You Paws ™, a subscription based service that shows you cute pictures of dogs or cats (or both for an additional fee).



- At Gives You Paws, anyone can upload pictures of their cats or dogs. The photos are then put through a two step process. First an automated algorithm tags pictures as either a cat or a dog (Phase I). Next, the photos that have been initially identified are put through another round of review, possibly with some human oversight, before being presented to the users (Phase II).



- Several models have already been developed with the data, and you can find their results here.



In [10]:
dogs_or_cats = pd.read_csv('gives_you_paws.csv')
dogs_or_cats.head()

actual model1 model2 model3 model4
0    cat    cat    dog    cat    dog
1    dog    dog    cat    cat    dog
2    dog    cat    cat    cat    dog
3    dog    dog    dog    cat    dog
4    cat    cat    cat    dog    dog

- Given this dataset, use pandas to create a baseline model (i.e. a model that just predicts the most common class) and answer the following questions:



In [12]:
dogs_or_cats.actual.value_counts()

dog    3254
cat    1746
Name: actual, dtype: int64

In [13]:
dogs_or_cats["baseline"] = dogs_or_cats.actual.value_counts().idxmax()
dogs_or_cats.head()

actual model1 model2 model3 model4 baseline
0    cat    cat    dog    cat    dog      dog
1    dog    dog    cat    cat    dog      dog
2    dog    cat    cat    cat    dog      dog
3    dog    dog    dog    cat    dog      dog
4    cat    cat    cat    dog    dog      dog

a. In terms of accuracy, how do the various models compare to the baseline model? Are any of the models better than the baseline?


In [14]:
models = list(dogs_or_cats.columns)
models = models[1:]
models

['model1', 'model2', 'model3', 'model4', 'baseline']

In [97]:
output = {}
for model in models:
    accuracy = (dogs_or_cats.actual == dogs_or_cats[model]).mean()
    output.update({model:accuracy})
    
output

{'model1': 0.8074,
 'model2': 0.6304,
 'model3': 0.5096,
 'model4': 0.7426,
 'baseline': 0.6508}

In [98]:
pd.DataFrame(list(output.items()), columns = ['model', 'accuracy'])

model  accuracy
0    model1    0.8074
1    model2    0.6304
2    model3    0.5096
3    model4    0.7426
4  baseline    0.6508

b. Suppose you are working on a team that solely deals with dog pictures. Which of these models would you recomend for Phase I? For Phase II?


In [27]:
subset = dogs_or_cats[dogs_or_cats.actual == 'dog']
subset.head()

actual model1 model2 model3 model4 baseline
1    dog    dog    cat    cat    dog      dog
2    dog    cat    cat    cat    dog      dog
3    dog    dog    dog    cat    dog      dog
5    dog    dog    dog    dog    dog      dog
8    dog    dog    cat    dog    dog      dog

In [28]:
(subset.actual == subset.model1).mean()

0.803318992009834

In [29]:
(subset.actual == subset.model2).mean()

0.49078057775046097

In [30]:
(subset.actual == subset.model3).mean()

0.5086047940995697

In [31]:
(subset.actual == subset.model4).mean()

0.9557467732022127

In [34]:
confusion_matrix(dogs_or_cats.actual, dogs_or_cats.model4, labels = ['cat', 'dog'])

array([[ 603, 1143],
       [ 144, 3110]])

In [36]:
subset1 = dogs_or_cats[dogs_or_cats.model1 == 'dog']
subset2 = dogs_or_cats[dogs_or_cats.model2 == 'dog']
subset3 = dogs_or_cats[dogs_or_cats.model3 == 'dog']
subset4 = dogs_or_cats[dogs_or_cats.model4 == 'dog']

In [99]:
model1_precision = (subset1.actual == subset1.model1).mean()
model1_precision

0.8900238338440586

In [100]:
model2_precision = (subset2.actual == subset2.model2).mean()
model2_precision

0.8931767337807607

In [101]:
model3_precision = (subset3.actual == subset3.model3).mean()
model3_precision

0.6598883572567783

In [102]:
model4_precision = (subset4.actual == subset4.model4).mean()
model4_precision

0.7312485304490948

        c. Suppose you are working on a team that solely deals with cat pictures. Which of these models would you recomend for Phase I? For Phase II?


In [59]:
from sklearn.metrics import classification_report

In [62]:
print("Model 1")
pd.DataFrame(classification_report(dogs_or_cats.actual, dogs_or_cats.model1,
                                   labels = ['cat', 'dog'],
                                   output_dict=True))

Model 1


cat          dog  accuracy    macro avg  weighted avg
precision     0.689772     0.890024    0.8074     0.789898      0.820096
recall        0.815006     0.803319    0.8074     0.809162      0.807400
f1-score      0.747178     0.844452    0.8074     0.795815      0.810484
support    1746.000000  3254.000000    0.8074  5000.000000   5000.000000

In [63]:
print("Model 2")
pd.DataFrame(classification_report(dogs_or_cats.actual, dogs_or_cats.model2,
                                   labels = ['cat', 'dog'],
                                   output_dict=True)).T

Model 2


precision    recall  f1-score    support
cat            0.484122  0.890607  0.627269  1746.0000
dog            0.893177  0.490781  0.633479  3254.0000
accuracy       0.630400  0.630400  0.630400     0.6304
macro avg      0.688649  0.690694  0.630374  5000.0000
weighted avg   0.750335  0.630400  0.631310  5000.0000

In [64]:
print("Model 3")
pd.DataFrame(classification_report(dogs_or_cats.actual, dogs_or_cats.model3,
                                   labels = ['cat', 'dog'],
                                   output_dict=True)).T

Model 3


precision    recall  f1-score    support
cat            0.358347  0.511455  0.421425  1746.0000
dog            0.659888  0.508605  0.574453  3254.0000
accuracy       0.509600  0.509600  0.509600     0.5096
macro avg      0.509118  0.510030  0.497939  5000.0000
weighted avg   0.554590  0.509600  0.521016  5000.0000

In [65]:
print("Model 4")
pd.DataFrame(classification_report(dogs_or_cats.actual, dogs_or_cats.model4,
                                   labels = ['cat', 'dog'],
                                   output_dict=True)).T

Model 4


precision    recall  f1-score    support
cat            0.807229  0.345361  0.483755  1746.0000
dog            0.731249  0.955747  0.828560  3254.0000
accuracy       0.742600  0.742600  0.742600     0.7426
macro avg      0.769239  0.650554  0.656157  5000.0000
weighted avg   0.757781  0.742600  0.708154  5000.0000

5. Follow the links below to read the documentation about each function, then apply those functions to the data from the previous problem.


- sklearn.metrics.accuracy_score
    - https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html


In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_true, y_pred, normalize=False)

- sklearn.metrics.precision_score
    - https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html


In [ ]:
from sklearn.metrics import precision_score

In [ ]:
precision_score(y_true, y_pred, average='macro')

In [ ]:
precision_score(y_true, y_pred, average='micro')

In [ ]:
precision_score(y_true, y_pred, average='weighted')

In [ ]:
precision_score(y_true, y_pred, average=None)

In [ ]:
precision_score(y_true, y_pred, average=None)

In [ ]:
precision_score(y_true, y_pred, average=None, zero_division=1)

- sklearn.metrics.recall_score
    - https://scikit-learn.org/stable/modules/generated/sklearn.metrics.recall_score.html


In [ ]:
from sklearn.metrics import recall_score

In [ ]:
precision_score(y_true, y_pred, average='macro')

In [ ]:
precision_score(y_true, y_pred, average='micro')

In [ ]:
precision_score(y_true, y_pred, average='weighted')

In [ ]:
precision_score(y_true, y_pred, average=None)

In [ ]:
precision_score(y_true, y_pred, average=None)

In [ ]:
precision_score(y_true, y_pred, average=None, zero_division=1)

- sklearn.metrics.classification_report
    - https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
target_names = ['class 0', 'class 1', 'class 2']
print(dogs_or_cats(y_true, y_pred, target_names=target_names))

In [ ]:
print(dogs_or_cats(y_true, y_pred, labels=[1, 2, 3]))