1. Create a new file named model_evaluation.py or model_evaluation.ipynb for these exercises.

## ✓

2. Given the following confusion matrix, evaluate (by hand) the model's performance.

|               | pred dog   | pred cat   |
|:------------  |-----------:|-----------:|
| actual dog    |         46 |         7  |
| actual cat    |         13 |         34 |




- **Values**
    - TP = 46
    - FP = 13
    - TN = 34
    - FN = 7

- **Accuracy**
    - (TP + TN) / (TP + FP + TN + FN)
        - (46 + 34) / (46 + 13 + 34 + 7)
            - 80 / 100
                - .8
- **Precision**
    - (TP) / (TP + FP)
        - 46 / (46 + 13)
            - 46 / 59
                - .77966
- **Recall**
    - (TP) / (TP + FN)
        - 46 / (46 + 7)
            - 46 / 53
                - .8679
- **F1 Score**
    - (2 * Precision * Recall) / (Precision + Recall)
        - (2 * .77966 * .8679) / (.77966 + .8679)
            - 1.3533 / 1.6476
                - .8214

    a. In the context of this problem, what is a false positive?


- FP = 13
    - predicted a dog 
    - actually a cat

    b. In the context of this problem, what is a false negative?


- FN = 7
    - predicted cat
    - actually dog

    c. How would you describe this model?
    


3. You are working as a datascientist working for Codeup Cody Creator (C3 for short), a rubber-duck manufacturing plant.



In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from pydataset import data

- Unfortunately, some of the rubber ducks that are produced will have defects. Your team has built several models that try to predict those defects, and the data from their predictions can be found here.



In [2]:
rubber_ducks = pd.read_csv('c3.csv')
rubber_ducks.head()

actual     model1  model2     model3
0  No Defect  No Defect  Defect  No Defect
1  No Defect  No Defect  Defect     Defect
2  No Defect  No Defect  Defect  No Defect
3  No Defect     Defect  Defect     Defect
4  No Defect  No Defect  Defect  No Defect

- Use the predictions dataset and pandas to help answer the following questions:


In [3]:
from sklearn.metrics import confusion_matrix

In [4]:
rubber_ducks = pd.melt(rubber_ducks, id_vars = 'actual', var_name = 'model', value_name = 'prediciton') 
rubber_ducks

actual   model prediciton
0    No Defect  model1  No Defect
1    No Defect  model1  No Defect
2    No Defect  model1  No Defect
3    No Defect  model1     Defect
4    No Defect  model1  No Defect
..         ...     ...        ...
595  No Defect  model3     Defect
596     Defect  model3  No Defect
597  No Defect  model3  No Defect
598  No Defect  model3     Defect
599  No Defect  model3     Defect

[600 rows x 3 columns]

In [5]:
y_true = rubber_ducks.actual
y_pred = rubber_ducks.prediciton

In [6]:
tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels = ['No Defect', 'Defect']).ravel()
tn, fp, fn, tp

(383, 169, 18, 30)

In [7]:
accuracy = (tp + tn) / (tp + tn + fp + fn)
recall = tp / (tp + fn)
precision = tp / (tp + fp)
f1_score = (2 * precision * recall) / (precision + recall)

- An internal team wants to investigate the cause of the manufacturing defects. They tell you that **they want to identify as many of the ducks that have a defect as possible**. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

I would use the precision evaluation metric. I would use this method because when determining as many of the rubber duck actually have defects as possible. And, precision tells us how good our model's positive predictions are, and does not take into account false negatives or true negatives

In [8]:
precision = tp / (tp + fp)
print("Rubber Duck Defect Precision is", duck_precision.round(3))

NameError: name 'duck_precision' is not defined

- Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, and portraying C3 in a bad light. The PR team has decided to launch a program that gives customers with a defective duck a vacation to Hawaii. **They need you to predict which ducks will have defects, but tell you they really don't want to accidentally give out a vacation package when the duck really doesn't have a defect.** Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

I would use the F1 score since we need to use precision as welll as recall.

In [ ]:
f1_score = (2 * precision * recall) / (precision + recall)
print("Rubber Duck Defect F1 Score is", precision.round(3))

4. You are working as a data scientist for Gives You Paws ™, a subscription based service that shows you cute pictures of dogs or cats (or both for an additional fee).



- At Gives You Paws, anyone can upload pictures of their cats or dogs. The photos are then put through a two step process. First an automated algorithm tags pictures as either a cat or a dog (Phase I). Next, the photos that have been initially identified are put through another round of review, possibly with some human oversight, before being presented to the users (Phase II).



- Several models have already been developed with the data, and you can find their results here.



In [9]:
dogs_or_cats = pd.read_csv('gives_you_paws.csv')
dogs_or_cats.head()

actual model1 model2 model3 model4
0    cat    cat    dog    cat    dog
1    dog    dog    cat    cat    dog
2    dog    cat    cat    cat    dog
3    dog    dog    dog    cat    dog
4    cat    cat    cat    dog    dog

In [10]:
dogs_or_cats = pd.melt(dogs_or_cats, id_vars = 'actual', var_name = 'model', value_name = 'prediciton') 
dogs_or_cats.head()

actual   model prediciton
0    cat  model1        cat
1    dog  model1        dog
2    dog  model1        cat
3    dog  model1        dog
4    cat  model1        cat

In [11]:
y_true = dogs_or_cats.actual
y_pred = dogs_or_cats.prediciton

In [12]:
tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels = ['cat', 'dog']).ravel()
tn, fp, fn, tp

(4474, 2510, 4040, 8976)

In [13]:
accuracy = (tp + tn) / (tp + tn + fp + fn)
recall = tp / (tp + fn)
precision = tp / (tp + fp)
f1_score = (2 * precision * recall) / (precision + recall)

- Given this dataset, use pandas to create a baseline model (i.e. a model that just predicts the most common class) and answer the following questions:



In [14]:
dogs_or_cats.actual.value_counts()

dog    13016
cat     6984
Name: actual, dtype: int64

In [15]:
dogs_or_cats['baseline_prediction'] = 'dog'
dogs_or_cats

actual   model prediciton baseline_prediction
0        cat  model1        cat                 dog
1        dog  model1        dog                 dog
2        dog  model1        cat                 dog
3        dog  model1        dog                 dog
4        cat  model1        cat                 dog
...      ...     ...        ...                 ...
19995    dog  model4        dog                 dog
19996    dog  model4        dog                 dog
19997    dog  model4        dog                 dog
19998    cat  model4        dog                 dog
19999    dog  model4        dog                 dog

[20000 rows x 4 columns]

a. In terms of accuracy, how do the various models compare to the baseline model? Are any of the models better than the baseline?


In [17]:
baseline_accuracy = (dogs_or_cats.actual == dogs_or_cats.baseline_prediction).mean()
baseline_accuracy 

0.6508

In [16]:
accuracy

0.6725

b. Suppose you are working on a team that solely deals with dog pictures. Which of these models would you recomend for Phase I? For Phase II?


In [20]:
# Phase 1
    # an automated algorithm tags pictures as either a cat or a dog
        # Accuracy
accuracy = (tp + tn) / (tp + tn + fp + fn)
accuracy

0.6725

In [19]:
# Phase 2
    # photos that have been initially identified are put through another round of review, possibly with some human oversight, before being presented to the users
        # F1 Score
f1_score = (2 * precision * recall) / (precision + recall)
f1_score

0.7326748836829647

        c. Suppose you are working on a team that solely deals with cat pictures. Which of these models would you recomend for Phase I? For Phase II?


In [21]:
# Phase 1
    # an automated algorithm tags pictures as either a cat or a dog
        # Accuracy
accuracy = (tp + tn) / (tp + tn + fp + fn)
accuracy

0.6725

In [22]:
# Phase 2
    # photos that have been initially identified are put through another round of review, possibly with some human oversight, before being presented to the users
        # F1 Score
f1_score = (2 * precision * recall) / (precision + recall)
f1_score

0.7326748836829647

5. Follow the links below to read the documentation about each function, then apply those functions to the data from the previous problem.


- sklearn.metrics.accuracy_score
    - https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html


In [24]:
from sklearn.metrics import accuracy_score

In [25]:
accuracy_score(y_true, y_pred, normalize=False)

13450

- sklearn.metrics.precision_score
    - https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html


In [26]:
from sklearn.metrics import precision_score

In [27]:
precision_score(y_true, y_pred, average='macro')

0.6534802650741569

In [28]:
precision_score(y_true, y_pred, average='micro')

0.6725

In [29]:
precision_score(y_true, y_pred, average='weighted')

0.692082903389327

In [30]:
precision_score(y_true, y_pred, average=None)

array([0.52548743, 0.7814731 ])

In [31]:
precision_score(y_true, y_pred, average=None)

array([0.52548743, 0.7814731 ])

In [32]:
precision_score(y_true, y_pred, average=None, zero_division=1)

array([0.52548743, 0.7814731 ])

- sklearn.metrics.recall_score
    - https://scikit-learn.org/stable/modules/generated/sklearn.metrics.recall_score.html


In [34]:
from sklearn.metrics import recall_score

In [35]:
precision_score(y_true, y_pred, average='macro')

0.6534802650741569

In [36]:
precision_score(y_true, y_pred, average='micro')

0.6725

In [37]:
precision_score(y_true, y_pred, average='weighted')

0.692082903389327

In [38]:
precision_score(y_true, y_pred, average=None)

array([0.52548743, 0.7814731 ])

In [39]:
precision_score(y_true, y_pred, average=None)

array([0.52548743, 0.7814731 ])

In [40]:
precision_score(y_true, y_pred, average=None, zero_division=1)

array([0.52548743, 0.7814731 ])

- sklearn.metrics.classification_report
    - https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html

In [41]:
from sklearn.metrics import classification_report

In [43]:
target_names = ['class 0', 'class 1', 'class 2']
print(dogs_or_cats(y_true, y_pred, target_names=target_names))

TypeError: 'DataFrame' object is not callable

In [44]:
print(dogs_or_cats(y_true, y_pred, labels=[1, 2, 3]))

TypeError: 'DataFrame' object is not callable